# Generated by Django 5.2.5 on 2025-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=250)),
                ('client_last_name', models.CharField(max_length=250)),
                ('client_phone_number', models.IntegerField(max_length=11)),
                ('client_address', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
