# Generated by Django 5.2.5 on 2025-08-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_client_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
            preserve_default=False,
        ),
    ]
