# Generated by Django 5.2.5 on 2025-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_client_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
