# Generated by Django 5.2.5 on 2025-08-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_client_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
